name: "User Report"
description: "make bad guy getting banned"

labels: "report"
title: "User Report"

body:
    
    - type: markdown
      attributes:
          value: |
               @user95401
          
    - type: input
      attributes:
          label: username or link (link pls)
      validations:
        required: true
          
    - type: input
      attributes:
        label: crime scene (mod id or issue number for example)
      validations:
        required: true
          
    - type: textarea
      attributes:
        label: "More..."
